import { NextRequest, NextResponse } from 'next/server'
import { z } from 'zod'
import { requireAuth } from '@/lib/api-auth'
import { prisma } from '@/lib/prisma'
import { logAudit } from '@/lib/audit'

const planSchema=z.object({action:z.literal('plan'),name:z.string().min(1),provider:z.string().optional(),type:z.enum(['HMO','LIFE_INSURANCE','RETIREMENT','WELLNESS','ALLOWANCE','OTHER']),description:z.string().optional(),employerShare:z.coerce.number().nonnegative(),employeeShare:z.coerce.number().nonnegative(),dependentLimit:z.coerce.number().int().nonnegative(),eligibilityMonths:z.coerce.number().int().nonnegative()})
const enrollSchema=z.object({action:z.literal('enroll'),employeeId:z.string().min(1),benefitPlanId:z.string().min(1),effectiveDate:z.string().min(1),memberNumber:z.string().optional(),employeeShare:z.coerce.number().nonnegative().optional(),employerShare:z.coerce.number().nonnegative().optional(),dependents:z.array(z.object({name:z.string().min(1),relationship:z.string().min(1),birthDate:z.string().optional()})).default([])})
const schema=z.discriminatedUnion('action',[planSchema,enrollSchema])
const admins=new Set(['SUPER_ADMIN','COMPANY_ADMIN','HR_MANAGER'])

export async function GET(){const {ctx,error}=await requireAuth();if(error)return error;const employee=await prisma.employee.findFirst({where:{companyId:ctx.companyId,userId:ctx.userId},select:{id:true}});const manage=admins.has(ctx.role);const [plans,employees]=await Promise.all([prisma.benefitPlan.findMany({where:{companyId:ctx.companyId},include:{enrollments:{where:manage?{}:{employeeId:employee?.id??'__none__'},include:{employee:{select:{id:true,firstName:true,lastName:true,employeeNo:true}}}}},orderBy:{name:'asc'}}),manage?prisma.employee.findMany({where:{companyId:ctx.companyId,isActive:true},select:{id:true,firstName:true,lastName:true,employeeNo:true},orderBy:{lastName:'asc'}}):Promise.resolve([])]);return NextResponse.json({plans,employees,canManage:manage})}
export async function POST(req:NextRequest){const {ctx,error}=await requireAuth();if(error)return error;if(!admins.has(ctx.role))return NextResponse.json({error:'Not authorized.'},{status:403});const parsed=schema.safeParse(await req.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:'Invalid benefit details.',details:parsed.error.flatten()},{status:422});if(parsed.data.action==='plan'){const {action,...data}=parsed.data;void action;const plan=await prisma.benefitPlan.create({data:{companyId:ctx.companyId,...data,provider:data.provider||null,description:data.description||null}});logAudit(ctx,'CREATE','BenefitPlan',plan.id,{description:`Created benefit plan ${plan.name}`}).catch(()=>{});return NextResponse.json({plan},{status:201})}const employee=await prisma.employee.findFirst({where:{id:parsed.data.employeeId,companyId:ctx.companyId},select:{id:true,hireDate:true}});const plan=await prisma.benefitPlan.findFirst({where:{id:parsed.data.benefitPlanId,companyId:ctx.companyId}});if(!employee||!plan)return NextResponse.json({error:'Employee or plan not found.'},{status:404});if(parsed.data.dependents.length>plan.dependentLimit)return NextResponse.json({error:`This plan allows up to ${plan.dependentLimit} dependent${plan.dependentLimit===1?'':'s'}.`},{status:422});const eligibleAt=new Date(employee.hireDate);eligibleAt.setMonth(eligibleAt.getMonth()+plan.eligibilityMonths);if(new Date(parsed.data.effectiveDate)<eligibleAt)return NextResponse.json({error:`Employee becomes eligible on ${eligibleAt.toLocaleDateString('en-PH')}.`},{status:422});const enrollment=await prisma.employeeBenefitEnrollment.upsert({where:{employeeId_benefitPlanId:{employeeId:employee.id,benefitPlanId:plan.id}},create:{employeeId:employee.id,benefitPlanId:plan.id,effectiveDate:new Date(parsed.data.effectiveDate),memberNumber:parsed.data.memberNumber||null,employeeShare:parsed.data.employeeShare??plan.employeeShare,employerShare:parsed.data.employerShare??plan.employerShare,dependents:parsed.data.dependents},update:{status:'ACTIVE',effectiveDate:new Date(parsed.data.effectiveDate),endDate:null,memberNumber:parsed.data.memberNumber||null,employeeShare:parsed.data.employeeShare??plan.employeeShare,employerShare:parsed.data.employerShare??plan.employerShare,dependents:parsed.data.dependents}});logAudit(ctx,'CREATE','BenefitEnrollment',enrollment.id,{description:`Enrolled employee in ${plan.name}`}).catch(()=>{});return NextResponse.json({enrollment},{status:201})}
