'use client'

import { useEffect, useState } from 'react'
import { Check, Loader2, Plus, Receipt, X } from 'lucide-react'
import { toast } from 'sonner'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'

type Claim = { id:string; category:string; description:string; expenseDate:string; amount:number; approvedAmount:number|null; status:string; receiptUrl:string|null; isLiquidation:boolean; cashAdvanceAmount:number|null; createdAt:string; employee:{firstName:string;lastName:string;employeeNo:string;department:{name:string}|null} }
const empty = { category:'Transportation', description:'', expenseDate:new Date().toISOString().slice(0,10), amount:'', receiptUrl:'', isLiquidation:false, cashAdvanceAmount:'' }

export function ExpensesClient({ portal = false }: { portal?: boolean }) {
  const [claims,setClaims]=useState<Claim[]>([]), [canApprove,setCanApprove]=useState(false), [loading,setLoading]=useState(true), [open,setOpen]=useState(false), [saving,setSaving]=useState(false)
  const [form,setForm]=useState(empty)
  const [receipt,setReceipt]=useState<File|null>(null)
  async function load(){setLoading(true);const r=await fetch('/api/expenses');const d=await r.json();setClaims(d.claims??[]);setCanApprove(Boolean(d.canApprove));setLoading(false)}
  useEffect(()=>{let active=true;fetch('/api/expenses').then(r=>r.json()).then(d=>{if(!active)return;setClaims(d.claims??[]);setCanApprove(Boolean(d.canApprove));setLoading(false)});return()=>{active=false}},[])
  async function submit(){setSaving(true);const r=await fetch('/api/expenses',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,amount:Number(form.amount),cashAdvanceAmount:form.cashAdvanceAmount?Number(form.cashAdvanceAmount):undefined})});const d=await r.json();if(!r.ok){setSaving(false);return toast.error(d.error??'Could not submit claim')}if(receipt){const fd=new FormData();fd.append('file',receipt);const upload=await fetch(`/api/expenses/${d.claim.id}/receipt`,{method:'POST',body:fd});if(!upload.ok){setSaving(false);return toast.error('Claim saved, but the receipt upload failed.')}}setSaving(false);toast.success('Expense claim submitted');setForm(empty);setReceipt(null);setOpen(false);void load()}
  async function review(id:string,status:'APPROVED'|'REJECTED'|'PAID'){const r=await fetch(`/api/expenses/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status})});if(!r.ok)return toast.error('Could not update claim');toast.success(`Claim ${status.toLowerCase()}`);void load()}
  const peso=(n:number|null)=>new Intl.NumberFormat('en-PH',{style:'currency',currency:'PHP'}).format(n??0)
  return <div className="space-y-5">
    <div className="flex items-center justify-between"><div><h1 className="text-2xl font-bold">{portal?'My Expenses':'Expense Claims & Liquidation'}</h1><p className="mt-1 text-sm text-gray-500">Reimbursements, receipts, and cash-advance liquidation in one workflow.</p></div><Button onClick={()=>setOpen(v=>!v)}><Plus className="mr-2 h-4 w-4"/>New claim</Button></div>
    {open&&<Card><CardHeader><CardTitle className="text-base">Submit expense</CardTitle></CardHeader><CardContent className="grid gap-3 md:grid-cols-2">
      <select className="h-9 rounded-md border px-3 text-sm" value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{['Transportation','Meals','Accommodation','Supplies','Communication','Medical','Other'].map(x=><option key={x}>{x}</option>)}</select>
      <Input type="date" value={form.expenseDate} onChange={e=>setForm({...form,expenseDate:e.target.value})}/><Input type="number" min="0" step="0.01" placeholder="Amount" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/><Input placeholder="Receipt URL (optional)" value={form.receiptUrl} onChange={e=>setForm({...form,receiptUrl:e.target.value})}/>
      <textarea className="min-h-20 rounded-md border px-3 py-2 text-sm md:col-span-2" placeholder="Business purpose and details" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/>
      <label className="text-sm md:col-span-2">Receipt (PDF or image, up to 10 MB)<Input type="file" accept="application/pdf,image/jpeg,image/png,image/webp" className="mt-1" onChange={e=>setReceipt(e.target.files?.[0]??null)}/></label>
      <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.isLiquidation} onChange={e=>setForm({...form,isLiquidation:e.target.checked})}/>Cash-advance liquidation</label>{form.isLiquidation&&<Input type="number" min="0" placeholder="Cash advance received" value={form.cashAdvanceAmount} onChange={e=>setForm({...form,cashAdvanceAmount:e.target.value})}/>}<div className="flex gap-2 md:col-span-2"><Button onClick={submit} disabled={saving||!form.amount||!form.description}>{saving&&<Loader2 className="mr-2 h-4 w-4 animate-spin"/>}Submit</Button><Button variant="outline" onClick={()=>setOpen(false)}>Cancel</Button></div>
    </CardContent></Card>}
    <Card><CardContent className="p-0">{loading?<p className="p-8 text-center text-sm text-gray-500">Loading claims…</p>:claims.length===0?<div className="p-12 text-center text-gray-400"><Receipt className="mx-auto mb-2 h-10 w-10"/><p>No expense claims yet.</p></div>:<div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b bg-gray-50 text-left"><th className="p-3">Employee</th><th className="p-3">Expense</th><th className="p-3">Date</th><th className="p-3 text-right">Amount</th><th className="p-3">Status</th><th className="p-3">Actions</th></tr></thead><tbody>{claims.map(c=><tr key={c.id} className="border-b"><td className="p-3"><b>{c.employee.firstName} {c.employee.lastName}</b><p className="text-xs text-gray-500">{c.employee.employeeNo}</p></td><td className="p-3"><b>{c.category}</b>{c.isLiquidation&&<span className="ml-2 rounded bg-blue-50 px-1.5 py-0.5 text-xs text-blue-700">Liquidation</span>}<p className="max-w-xs truncate text-xs text-gray-500">{c.description}</p>{c.receiptUrl&&<a className="text-xs text-blue-600 underline" href={c.receiptUrl} target="_blank">View receipt</a>}</td><td className="p-3">{new Date(c.expenseDate).toLocaleDateString('en-PH')}</td><td className="p-3 text-right font-semibold">{peso(Number(c.amount))}</td><td className="p-3"><span className="rounded-full bg-gray-100 px-2 py-1 text-xs font-semibold">{c.status}</span></td><td className="p-3">{canApprove&&c.status==='PENDING'&&<div className="flex gap-1"><Button size="sm" onClick={()=>review(c.id,'APPROVED')}><Check className="h-3 w-3"/></Button><Button size="sm" variant="outline" onClick={()=>review(c.id,'REJECTED')}><X className="h-3 w-3"/></Button></div>}{canApprove&&c.status==='APPROVED'&&<Button size="sm" variant="outline" onClick={()=>review(c.id,'PAID')}>Mark paid</Button>}</td></tr>)}</tbody></table></div>}</CardContent></Card>
  </div>
}
