import { NextRequest, NextResponse } from 'next/server'
import { z } from 'zod'
import { requireAuth } from '@/lib/api-auth'
import { requireHrisProApi } from '@/lib/hris-pro'
import { prisma } from '@/lib/prisma'

const signatory = z.object({ id: z.string(), role: z.enum(['CANDIDATE', 'COMPANY']), name: z.string(), title: z.string().optional().default(''), email: z.string().optional().default(''), required: z.boolean().default(true) })
const createSchema = z.object({ applicationId: z.string(), templateId: z.string().optional().nullable(), type: z.enum(['JOB_OFFER', 'EMPLOYMENT_CONTRACT', 'OTHER']), title: z.string().min(2), content: z.string().min(10), paperSize: z.enum(['A4', 'LETTER', 'LEGAL']).default('A4'), signatories: z.array(signatory).min(1), expiresAt: z.string().optional().nullable(), variables: z.record(z.string(), z.string().max(5_000)).optional().default({}) })

async function context() { const auth = await requireAuth(['SUPER_ADMIN', 'COMPANY_ADMIN', 'HR_MANAGER']); if (auth.error) return auth; const gate = await requireHrisProApi(auth.ctx.companyId); return { ...auth, error: gate } }
export async function GET(request: NextRequest) { const { ctx, error } = await context(); if (error) return error; if (!ctx) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 }); const applicationId = new URL(request.url).searchParams.get('applicationId'); const documents = await prisma.recruitmentDocument.findMany({ where: { companyId: ctx.companyId, ...(applicationId ? { applicationId } : {}) }, orderBy: { updatedAt: 'desc' } }); return NextResponse.json({ documents }) }
export async function POST(request: NextRequest) { const { ctx, error } = await context(); if (error) return error; if (!ctx) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 }); const parsed = createSchema.safeParse(await request.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ error: parsed.error.flatten() }, { status: 400 }); const application = await prisma.jobApplication.findFirst({ where: { id: parsed.data.applicationId, companyId: ctx.companyId }, select: { id: true, firstName: true, lastName: true, email: true, jobPost: { select: { title: true, department: true, location: true } }, company: { select: { name: true, tradeName: true } } } }); if (!application) return NextResponse.json({ error: 'Candidate not found' }, { status: 404 }); const candidateName = `${application.firstName} ${application.lastName}`; const variables: Record<string, string> = { ...parsed.data.variables, candidate_name: candidateName, candidate_email: application.email, job_title: application.jobPost.title, department: application.jobPost.department ?? '', location: application.jobPost.location ?? '', company_name: application.company.tradeName || application.company.name, issue_date: new Intl.DateTimeFormat('en-PH', { dateStyle: 'long' }).format(new Date()) }; const render = (value: string) => value.replace(/{{\s*([a-z0-9_]+)\s*}}/gi, (match, key: string) => variables[key.toLowerCase()] ?? match); const signatories = parsed.data.signatories.map(item => item.role === 'CANDIDATE' ? { ...item, name: candidateName, email: application.email } : item); const document = await prisma.recruitmentDocument.create({ data: { companyId: ctx.companyId, applicationId: application.id, templateId: parsed.data.templateId, type: parsed.data.type, title: render(parsed.data.title), content: render(parsed.data.content), paperSize: parsed.data.paperSize, signatories, expiresAt: parsed.data.expiresAt ? new Date(parsed.data.expiresAt) : null, createdBy: ctx.userId } }); return NextResponse.json({ document, signingUrl: `/sign/${document.publicToken}` }, { status: 201 }) }
export async function PATCH(request: NextRequest) { const { ctx, error } = await context(); if (error) return error; if (!ctx) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 }); const body = await request.json().catch(() => null) as { id?: string; action?: string }; if (!body?.id || !['SEND', 'VOID'].includes(body.action ?? '')) return NextResponse.json({ error: 'Invalid action' }, { status: 400 }); const existing = await prisma.recruitmentDocument.findFirst({ where: { id: body.id, companyId: ctx.companyId }, select: { id: true } }); if (!existing) return NextResponse.json({ error: 'Document not found' }, { status: 404 }); const document = await prisma.recruitmentDocument.update({ where: { id: existing.id }, data: body.action === 'SEND' ? { status: 'SENT', sentAt: new Date() } : { status: 'VOID' } }); return NextResponse.json({ document, signingUrl: `/sign/${document.publicToken}` }) }

