'use client'
import { useEffect, useState } from 'react'
import { HeartPulse, Plus, Trash2 } from 'lucide-react'
import { toast } from 'sonner'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'

type Employee={id:string;firstName:string;lastName:string;employeeNo:string}
type Enrollment={id:string;status:string;memberNumber:string|null;employee:Employee}
type Plan={id:string;name:string;provider:string|null;type:string;description:string|null;employerShare:number;employeeShare:number;dependentLimit:number;eligibilityMonths:number;isActive:boolean;enrollments:Enrollment[]}
type Dependent={name:string;relationship:string;birthDate:string}
const emptyPlan={action:'plan',name:'',provider:'',type:'HMO',description:'',employerShare:'0',employeeShare:'0',dependentLimit:'0',eligibilityMonths:'0'}
const emptyDependent=():Dependent=>({name:'',relationship:'',birthDate:''})

export function BenefitsClient({portal=false}:{portal?:boolean}){
 const[plans,setPlans]=useState<Plan[]>([]),[employees,setEmployees]=useState<Employee[]>([]),[canManage,setCanManage]=useState(false),[loading,setLoading]=useState(true),[mode,setMode]=useState<'plan'|'enroll'|null>(null),[plan,setPlan]=useState(emptyPlan)
 const[enroll,setEnroll]=useState({action:'enroll',employeeId:'',benefitPlanId:'',effectiveDate:new Date().toISOString().slice(0,10),memberNumber:'',dependents:[] as Dependent[]})
 async function load(){setLoading(true);const d=await fetch('/api/benefits').then(r=>r.json());setPlans(d.plans??[]);setEmployees(d.employees??[]);setCanManage(Boolean(d.canManage));setLoading(false)}
 useEffect(()=>{let active=true;fetch('/api/benefits').then(r=>r.json()).then(d=>{if(active){setPlans(d.plans??[]);setEmployees(d.employees??[]);setCanManage(Boolean(d.canManage));setLoading(false)}});return()=>{active=false}},[])
 async function save(body:unknown){const r=await fetch('/api/benefits',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)return toast.error(d.error??'Could not save benefit');toast.success('Benefits updated');setMode(null);setPlan(emptyPlan);void load()}
 async function endEnrollment(id:string){const r=await fetch(`/api/benefits/enrollments/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:'ENDED'})});if(!r.ok)return toast.error('Could not end enrollment');toast.success('Enrollment ended');void load()}
 const peso=(n:number)=>new Intl.NumberFormat('en-PH',{style:'currency',currency:'PHP'}).format(Number(n))
 const selectedPlan=plans.find(x=>x.id===enroll.benefitPlanId)
 const updateDependent=(index:number,field:keyof Dependent,value:string)=>setEnroll(current=>({...current,dependents:current.dependents.map((dependent,i)=>i===index?{...dependent,[field]:value}:dependent)}))
 const addDependent=()=>setEnroll(current=>({...current,dependents:[...current.dependents,emptyDependent()]}))
 const removeDependent=(index:number)=>setEnroll(current=>({...current,dependents:current.dependents.filter((_,i)=>i!==index)}))
 return <div className="space-y-5">
  <div className="flex flex-wrap items-center justify-between gap-2"><div><h1 className="text-2xl font-bold">{portal?'My Benefits':'Benefits & HMO'}</h1><p className="text-sm text-gray-500">Plans, enrollment, dependents, and payroll-linked premiums.</p></div>{canManage&&<div className="flex gap-2"><Button variant="outline" onClick={()=>setMode('enroll')}><Plus className="mr-2 h-4 w-4"/>Enroll employee</Button><Button onClick={()=>setMode('plan')}><Plus className="mr-2 h-4 w-4"/>New plan</Button></div>}</div>
  {mode==='plan'&&<Card><CardHeader><CardTitle className="text-base">Create benefit plan</CardTitle></CardHeader><CardContent className="grid gap-3 md:grid-cols-3"><Input placeholder="Plan name" value={plan.name} onChange={e=>setPlan({...plan,name:e.target.value})}/><Input placeholder="Provider" value={plan.provider} onChange={e=>setPlan({...plan,provider:e.target.value})}/><select className="h-9 rounded-md border px-3 text-sm" value={plan.type} onChange={e=>setPlan({...plan,type:e.target.value})}>{['HMO','LIFE_INSURANCE','RETIREMENT','WELLNESS','ALLOWANCE','OTHER'].map(x=><option key={x}>{x}</option>)}</select><Input type="number" min="0" placeholder="Employer share/month" value={plan.employerShare} onChange={e=>setPlan({...plan,employerShare:e.target.value})}/><Input type="number" min="0" placeholder="Employee share/month" value={plan.employeeShare} onChange={e=>setPlan({...plan,employeeShare:e.target.value})}/><Input type="number" min="0" placeholder="Dependent limit" value={plan.dependentLimit} onChange={e=>setPlan({...plan,dependentLimit:e.target.value})}/><Input type="number" min="0" placeholder="Eligibility months" value={plan.eligibilityMonths} onChange={e=>setPlan({...plan,eligibilityMonths:e.target.value})}/><Input className="md:col-span-2" placeholder="Description" value={plan.description} onChange={e=>setPlan({...plan,description:e.target.value})}/><div className="flex gap-2 md:col-span-3"><Button onClick={()=>save({...plan,employerShare:+plan.employerShare,employeeShare:+plan.employeeShare,dependentLimit:+plan.dependentLimit,eligibilityMonths:+plan.eligibilityMonths})} disabled={!plan.name}>Save</Button><Button variant="outline" onClick={()=>setMode(null)}>Cancel</Button></div></CardContent></Card>}
  {mode==='enroll'&&<Card><CardHeader><CardTitle className="text-base">Enroll employee</CardTitle></CardHeader><CardContent className="grid gap-3 md:grid-cols-2"><select className="h-9 rounded-md border px-3 text-sm" value={enroll.employeeId} onChange={e=>setEnroll({...enroll,employeeId:e.target.value})}><option value="">Select employee</option>{employees.map(x=><option key={x.id} value={x.id}>{x.lastName}, {x.firstName} · {x.employeeNo}</option>)}</select><select className="h-9 rounded-md border px-3 text-sm" value={enroll.benefitPlanId} onChange={e=>setEnroll({...enroll,benefitPlanId:e.target.value,dependents:[]})}><option value="">Select plan</option>{plans.filter(x=>x.isActive).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><Input type="date" value={enroll.effectiveDate} onChange={e=>setEnroll({...enroll,effectiveDate:e.target.value})}/><Input placeholder="Member number" value={enroll.memberNumber} onChange={e=>setEnroll({...enroll,memberNumber:e.target.value})}/><div className="space-y-3 md:col-span-2"><div className="flex items-center justify-between gap-3"><div><p className="text-sm font-medium">Dependents</p><p className="text-xs text-gray-500">{selectedPlan?`Add up to ${selectedPlan.dependentLimit} dependent${selectedPlan.dependentLimit===1?'':'s'}.`:'Select a plan to add dependents.'}</p></div><Button type="button" variant="outline" size="sm" onClick={addDependent} disabled={!selectedPlan||enroll.dependents.length>=selectedPlan.dependentLimit}><Plus className="mr-1 h-4 w-4"/>Add dependent</Button></div>{enroll.dependents.map((dependent,index)=><div key={index} className="grid gap-2 rounded-lg border bg-gray-50 p-3 md:grid-cols-[1fr_1fr_160px_36px]"><Input aria-label={`Dependent ${index+1} name`} placeholder="Full name" value={dependent.name} onChange={e=>updateDependent(index,'name',e.target.value)}/><Input aria-label={`Dependent ${index+1} relationship`} placeholder="Relationship" value={dependent.relationship} onChange={e=>updateDependent(index,'relationship',e.target.value)}/><Input aria-label={`Dependent ${index+1} birth date`} type="date" value={dependent.birthDate} onChange={e=>updateDependent(index,'birthDate',e.target.value)}/><Button type="button" variant="ghost" size="icon" aria-label={`Remove dependent ${index+1}`} onClick={()=>removeDependent(index)}><Trash2 className="h-4 w-4 text-red-600"/></Button></div>)}</div><div className="flex gap-2 md:col-span-2"><Button onClick={()=>save({...enroll,dependents:enroll.dependents.map(({name,relationship,birthDate})=>({name:name.trim(),relationship:relationship.trim(),...(birthDate?{birthDate}:{})}))})} disabled={!enroll.employeeId||!enroll.benefitPlanId||enroll.dependents.some(x=>!x.name.trim()||!x.relationship.trim())}>Enroll</Button><Button variant="outline" onClick={()=>setMode(null)}>Cancel</Button></div></CardContent></Card>}
  {loading?<p className="py-10 text-center">Loading benefits…</p>:plans.length===0?<Card><CardContent className="py-16 text-center text-gray-400"><HeartPulse className="mx-auto mb-3 h-12 w-12"/>No benefit plans configured.</CardContent></Card>:<div className="grid gap-4 lg:grid-cols-2">{plans.map(p=><Card key={p.id}><CardHeader><CardTitle className="flex justify-between text-base"><span>{p.name}</span><span className="rounded bg-blue-50 px-2 py-1 text-xs text-blue-700">{p.type.replaceAll('_',' ')}</span></CardTitle><p className="text-xs text-gray-500">{p.provider||'No provider'} · {p.enrollments.length} enrolled</p></CardHeader><CardContent><p className="mb-3 text-sm text-gray-600">{p.description||'No description'}</p><div className="grid grid-cols-2 gap-2 rounded-lg bg-gray-50 p-3 text-xs"><span>Employer/month<b className="block">{peso(p.employerShare)}</b></span><span>Employee/month<b className="block">{peso(p.employeeShare)}</b></span><span>Dependents<b className="block">Up to {p.dependentLimit}</b></span><span>Eligibility<b className="block">{p.eligibilityMonths} months</b></span></div>{p.enrollments.map(e=><div key={e.id} className="mt-2 flex items-center justify-between border-t pt-2 text-sm"><span>{e.employee.firstName} {e.employee.lastName}<small className="ml-2 text-gray-400">{e.memberNumber||''}</small></span><span className="flex gap-2"><b className="text-xs text-emerald-600">{e.status}</b>{canManage&&e.status==='ACTIVE'&&<button className="text-xs text-red-600 underline" onClick={()=>endEnrollment(e.id)}>End</button>}</span></div>)}</CardContent></Card>)}</div>}
 </div>
}
