'use client'

import { useEffect, useState } from 'react'
import Link from 'next/link'
import { Award, BookOpen, Plus } from 'lucide-react'
import { toast } from 'sonner'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'

type Employee = { id:string; firstName:string; lastName:string; employeeNo:string }
type Enrollment = { id:string; status:string; dueDate:string|null; completedAt:string|null; score:number|null; employee:Employee }
type Course = { id:string; title:string; provider:string|null; category:string|null; durationHours:number|null; status:string; enrollments:Enrollment[] }
type Certification = { id:string; name:string; issuingBody:string|null; credentialId:string|null; issuedDate:string|null; expiryDate:string|null; certificateUrl:string|null; employee:Employee }
const renderedAt = Date.now()
const certificateWarningCutoff = renderedAt + 90 * 86400000

export function LearningClient({ portal=false }:{ portal?:boolean }) {
  const [courses,setCourses]=useState<Course[]>([]), [certifications,setCertifications]=useState<Certification[]>([]), [employees,setEmployees]=useState<Employee[]>([]), [canManage,setCanManage]=useState(false), [loading,setLoading]=useState(true), [mode,setMode]=useState<'course'|'enroll'|'cert'|null>(null)
  const [course,setCourse]=useState({action:'course',title:'',provider:'',category:'',description:'',durationHours:'',validityMonths:''})
  const [enroll,setEnroll]=useState({action:'enroll',courseId:'',employeeId:'',dueDate:''})
  const [cert,setCert]=useState({action:'certification',employeeId:'',name:'',issuingBody:'',credentialId:'',issuedDate:'',expiryDate:'',certificateUrl:'',notes:''})
  async function load(){setLoading(true);const d=await fetch('/api/learning').then(r=>r.json());setCourses(d.courses??[]);setCertifications(d.certifications??[]);setEmployees(d.employees??[]);setCanManage(Boolean(d.canManage));setLoading(false)}
  useEffect(()=>{let active=true;fetch('/api/learning').then(r=>r.json()).then(d=>{if(active){setCourses(d.courses??[]);setCertifications(d.certifications??[]);setEmployees(d.employees??[]);setCanManage(Boolean(d.canManage));setLoading(false)}});return()=>{active=false}},[])
  async function save(body:unknown){const r=await fetch('/api/learning',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)return toast.error(d.error??'Could not save record');toast.success('Learning record saved');setMode(null);void load()}
  async function complete(id:string){const score=window.prompt('Completion score (0-100), optional')||undefined;const r=await fetch(`/api/learning/enrollments/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:'COMPLETED',score})});if(!r.ok)return toast.error('Could not complete course');toast.success('Course marked complete');void load()}
  const expired=(date:string|null)=>Boolean(date&&new Date(date).getTime()<renderedAt)
  const soon=(date:string|null)=>Boolean(date&&!expired(date)&&new Date(date).getTime()<=certificateWarningCutoff)
  return <div className="space-y-5">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold">{portal?'My Learning & Certifications':'Learning & Certifications'}</h1><p className="text-sm text-gray-500">Training assignments, completion records, credentials, and expiry tracking.</p></div>{canManage&&<div className="flex flex-wrap gap-2"><Button variant="outline" onClick={()=>setMode('enroll')}><Plus className="mr-1 h-4 w-4"/>Assign course</Button><Button variant="outline" onClick={()=>setMode('cert')}><Award className="mr-1 h-4 w-4"/>Add certification</Button><Button onClick={()=>setMode('course')}><Plus className="mr-1 h-4 w-4"/>New course</Button></div>}</div>
    {mode==='course'&&<Card><CardHeader><CardTitle>Create course</CardTitle></CardHeader><CardContent className="grid gap-3 md:grid-cols-3"><Input placeholder="Course title" value={course.title} onChange={e=>setCourse({...course,title:e.target.value})}/><Input placeholder="Provider" value={course.provider} onChange={e=>setCourse({...course,provider:e.target.value})}/><Input placeholder="Category" value={course.category} onChange={e=>setCourse({...course,category:e.target.value})}/><Input type="number" min="0" placeholder="Duration hours" value={course.durationHours} onChange={e=>setCourse({...course,durationHours:e.target.value})}/><Input type="number" min="1" placeholder="Certificate validity months" value={course.validityMonths} onChange={e=>setCourse({...course,validityMonths:e.target.value})}/><Input placeholder="Description" value={course.description} onChange={e=>setCourse({...course,description:e.target.value})}/><div className="flex gap-2 md:col-span-3"><Button disabled={!course.title} onClick={()=>save({...course,durationHours:course.durationHours?+course.durationHours:undefined,validityMonths:course.validityMonths?+course.validityMonths:undefined})}>Save course</Button><Button variant="outline" onClick={()=>setMode(null)}>Cancel</Button></div></CardContent></Card>}
    {mode==='enroll'&&<Card><CardHeader><CardTitle>Assign course</CardTitle></CardHeader><CardContent className="grid gap-3 md:grid-cols-3"><select className="h-9 rounded-md border px-3 text-sm" value={enroll.employeeId} onChange={e=>setEnroll({...enroll,employeeId:e.target.value})}><option value="">Select employee</option>{employees.map(e=><option key={e.id} value={e.id}>{e.lastName}, {e.firstName} · {e.employeeNo}</option>)}</select><select className="h-9 rounded-md border px-3 text-sm" value={enroll.courseId} onChange={e=>setEnroll({...enroll,courseId:e.target.value})}><option value="">Select course</option>{courses.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select><Input type="date" value={enroll.dueDate} onChange={e=>setEnroll({...enroll,dueDate:e.target.value})}/><div className="flex gap-2 md:col-span-3"><Button disabled={!enroll.employeeId||!enroll.courseId} onClick={()=>save(enroll)}>Assign</Button><Button variant="outline" onClick={()=>setMode(null)}>Cancel</Button></div></CardContent></Card>}
    {mode==='cert'&&<Card><CardHeader><CardTitle>Add certification</CardTitle></CardHeader><CardContent className="grid gap-3 md:grid-cols-3"><select className="h-9 rounded-md border px-3 text-sm" value={cert.employeeId} onChange={e=>setCert({...cert,employeeId:e.target.value})}><option value="">Select employee</option>{employees.map(e=><option key={e.id} value={e.id}>{e.lastName}, {e.firstName}</option>)}</select><Input placeholder="Certification name" value={cert.name} onChange={e=>setCert({...cert,name:e.target.value})}/><Input placeholder="Issuing body" value={cert.issuingBody} onChange={e=>setCert({...cert,issuingBody:e.target.value})}/><Input placeholder="Credential ID" value={cert.credentialId} onChange={e=>setCert({...cert,credentialId:e.target.value})}/><Input type="date" value={cert.issuedDate} onChange={e=>setCert({...cert,issuedDate:e.target.value})}/><Input type="date" value={cert.expiryDate} onChange={e=>setCert({...cert,expiryDate:e.target.value})}/><Input className="md:col-span-2" placeholder="Certificate URL" value={cert.certificateUrl} onChange={e=>setCert({...cert,certificateUrl:e.target.value})}/><Input placeholder="Notes" value={cert.notes} onChange={e=>setCert({...cert,notes:e.target.value})}/><div className="flex gap-2 md:col-span-3"><Button disabled={!cert.employeeId||!cert.name} onClick={()=>save(cert)}>Save certification</Button><Button variant="outline" onClick={()=>setMode(null)}>Cancel</Button></div></CardContent></Card>}
    {loading?<p className="py-12 text-center">Loading learning records…</p>:<><div className="grid gap-4 lg:grid-cols-2">{courses.map(c=><Card key={c.id}><CardHeader><CardTitle className="flex items-center justify-between gap-2 text-base"><span className="flex items-center gap-2"><BookOpen className="h-4 w-4"/>{c.title}</span><span className="rounded bg-gray-100 px-2 py-1 text-[10px]">{c.status}</span></CardTitle><p className="text-xs text-gray-500">{c.provider||'Internal'}{c.category?` · ${c.category}`:''}{c.durationHours?` · ${c.durationHours} hours`:''}</p></CardHeader><CardContent><div className="mb-3"><Button asChild size="sm" variant="outline"><Link href={canManage?`/learning/${c.id}/builder`:`/portal/learning/${c.id}`}>{canManage?'Open builder':'Start course'}</Link></Button></div>{c.enrollments.length===0?<p className="text-sm text-gray-400">No employees assigned.</p>:c.enrollments.map(e=><div key={e.id} className="flex items-center justify-between border-t py-2 text-sm"><span>{e.employee.firstName} {e.employee.lastName}<small className="ml-2 text-gray-400">{e.dueDate?`Due ${new Date(e.dueDate).toLocaleDateString('en-PH')}`:''}</small></span><span className="flex items-center gap-2"><b className="text-xs">{e.status.replace('_',' ')}</b>{canManage&&e.status!=='COMPLETED'&&<button className="text-xs text-blue-600 underline" onClick={()=>complete(e.id)}>Complete</button>}</span></div>)}</CardContent></Card>)}</div><Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Award className="h-4 w-4"/>Certifications</CardTitle></CardHeader><CardContent>{certifications.length===0?<p className="text-sm text-gray-400">No certifications recorded.</p>:certifications.map(c=><div key={c.id} className="flex flex-wrap items-center justify-between gap-2 border-t py-3 text-sm"><span><b>{c.name}</b><small className="block text-gray-500">{c.employee.firstName} {c.employee.lastName}{c.issuingBody?` · ${c.issuingBody}`:''}</small></span><span className={`text-xs font-medium ${expired(c.expiryDate)?'text-red-600':soon(c.expiryDate)?'text-amber-600':'text-emerald-600'}`}>{c.expiryDate?(expired(c.expiryDate)?'Expired ':soon(c.expiryDate)?'Expires soon ':'Expires ')+new Date(c.expiryDate).toLocaleDateString('en-PH'):'No expiry'}</span></div>)}</CardContent></Card></>}
  </div>
}
